Imported sbt-extras, and reworked the run_sbt to use it. Also removed existing sbt-launcher code

diff --git a/bin/common b/bin/common
--- a/bin/common
+++ b/bin/common
@@ -227,34 +227,32 @@ universal_packaging_default_web_proc() {
 run_sbt()
 {
   local home=$1
-  local launcher=$2
-  local tasks=$3
+  local tasks=$2
 
-  #if [ ${maxSbtHeap:-""} == "" ]; then
-    case $(ulimit -u) in
-    32768) # PX Dyno
-      maxSbtHeap=6144
-      ;;
-    *)     # 2X Dyno
-      maxSbtHeap=1024
-      ;;
-    esac
-  #fi
-
-  JAVA_OPTS="-Xms768M -Xmx${maxSbtHeap}M -Xss4M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled"
-  JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF8 -Dsbt.log.noformat=true"
-  JAVA_OPTS="$JAVA_OPTS -Duser.home=$home"
-  JAVA_OPTS="$JAVA_OPTS -Divy.default.ivy.user.dir=$home/.ivy2"
-  JAVA_OPTS="$JAVA_OPTS -Dsbt.global.base=$home"
+  case $(ulimit -u) in
+  32768) # PX Dyno
+    maxSbtHeap=6144
+    ;;
+  *)     # 2X Dyno
+    maxSbtHeap=1024
+    ;;
+  esac
 
   status "Running: sbt $tasks"
-  #HOME="$home" java $JAVA_OPTS -jar $launcher $tasks < /dev/null 2>&1 | sed -u 's/^/       /'
+  HOME="$home" sbt -sbt-dir $home \
+    -ivy $home/.ivy2 \
+    -sbt-launch-dir $home/bin \
+    -Duser.home=$home \
+    -Divy.default.ivy.user.dir=$home/.ivy2 \
+    -Dfile.encoding=UTF8 \
+    -Dsbt.global.base=$home \
+    -Dsbt.log.noformat=true \
+    -no-colors -batch \
+    $tasks < /dev/null 2>&1 | sed -u 's/^/       /'
 
-  opt/sbt -sbt-dir $home/.sbt_home -ivy $home/.ivy2 -batch $tasks
-
-  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-    error "Failed to run sbt task: $tasks"
-  fi
+  # if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  #   error "Failed to run sbt task: $tasks"
+  # fi
 }
 
 cache_copy() {
