Fix shellcheck issues, add validation to CI (#262)

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,24 +4,31 @@
 # fail fast
 set -e
 
+# shellcheck disable=SC2034  # Used by buildpack-stdlib-v7.sh logging functions, will be removed soon
 BPLOG_PREFIX="buildpack.scala"
 
 BASE_DIR="$(pwd)"
-BP_DIR=$(cd $(dirname $0)/..; pwd) # absolute path
+BP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)" # absolute path
+# shellcheck disable=SC2034  # Used in sourced scripts
 BIN_DIR=$BP_DIR/bin
 OPT_DIR=$BP_DIR/opt
 LIB_DIR=$BP_DIR/lib
-. $LIB_DIR/common.sh
-. $LIB_DIR/properties.sh
-. $LIB_DIR/failures.sh
-. $LIB_DIR/metrics.sh
+# shellcheck source=lib/common.sh
+. "$LIB_DIR/common.sh"
+# shellcheck source=lib/properties.sh
+. "$LIB_DIR/properties.sh"
+# shellcheck source=lib/failures.sh
+. "$LIB_DIR/failures.sh"
+# shellcheck source=lib/metrics.sh
+. "$LIB_DIR/metrics.sh"
 
 # parse args
-APP_BUILD_DIR=$(cd $1; pwd)
+APP_BUILD_DIR=$(cd "$1"; pwd)
 CACHE_DIR=$2
 ENV_DIR=$3
 
-source $LIB_DIR/buildpack-stdlib-v7.sh
+# shellcheck disable=SC1091  # buildpack-stdlib-v7.sh is excluded from shellcheck
+source "$LIB_DIR/buildpack-stdlib-v7.sh"
 
 metrics::init "${CACHE_DIR}" "scala"
 metrics::setup
@@ -32,7 +39,7 @@ if [ -z "${CNB_STACK_ID:-}" ]; then
   # cache if the path is different.
   if is_app_dir "$APP_BUILD_DIR"; then
     BUILD_DIR="/tmp/scala_buildpack_build_dir"
-    mv $APP_BUILD_DIR $BUILD_DIR
+    mv "$APP_BUILD_DIR" "$BUILD_DIR"
   else
     BUILD_DIR="$APP_BUILD_DIR"
   fi
@@ -43,13 +50,15 @@ if [ -z "${CNB_STACK_ID:-}" ]; then
   sedReplace="sed -e s/[\/&]/\\\&/g"
   escAppBuildDir="$(echo "$APP_BUILD_DIR" | $sedReplace)"
   escBuildDir="$(echo "$BUILD_DIR" | $sedReplace)"
-  export PATH=$(echo "$PATH" | sed -e s/$escAppBuildDir/$escBuildDir/g)
-  export GEM_PATH=$(echo "$GEM_PATH" | sed -e s/$escAppBuildDir/$escBuildDir/g)
+  PATH=${PATH//"$escAppBuildDir"/"$escBuildDir"}
+  export PATH
+  GEM_PATH=${GEM_PATH//"$escAppBuildDir"/"$escBuildDir"}
+  export GEM_PATH
 else
   BUILD_DIR="$APP_BUILD_DIR"
 fi
 
-export_env $ENV_DIR "." "JAVA_OPTS"
+export_env "$ENV_DIR" "." "JAVA_OPTS"
 
 # Set system properties as env vars
 SYSPROPFILE="$BUILD_DIR/system.properties"
@@ -74,7 +83,7 @@ SBT_CLEAN=$(get_property "$SYSPROPFILE" "sbt.clean" "${SBT_CLEAN:-false}")
 install_jdk "$BUILD_DIR" "$CACHE_DIR"
 
 #create the cache dir if it doesn't exist
-mkdir -p $CACHE_DIR
+mkdir -p "$CACHE_DIR"
 
 # home directory from perspective of SBT; we rename
 # it because otherwise the project root and $HOME
@@ -86,12 +95,12 @@ SBT_USER_HOME_ABSOLUTE="$BUILD_DIR/$SBT_USER_HOME"
 SBT_BINDIR="$SBT_USER_HOME"/bin
 
 # chdir as sbt expects
-cd $BUILD_DIR
+cd "$BUILD_DIR"
 
 # unpack cache
 CACHED_DIRS="$SBT_USER_HOME target project/target project/boot .coursier"
 for DIR in $CACHED_DIRS; do
-  cache_copy $DIR $CACHE_DIR $BUILD_DIR
+  cache_copy "$DIR" "$CACHE_DIR" "$BUILD_DIR"
 done
 
 # these are preliminary checks. actual version check happens below when attempting to download sbt boot.properties
@@ -99,7 +108,7 @@ if ! test -e project/build.properties; then
   error "Your scala project must include project/build.properties and define sbt.version"
 fi
 
-if ! (has_supported_sbt_version ${BUILD_DIR} || has_supported_sbt_1_version ${BUILD_DIR}); then
+if ! (has_supported_sbt_version "${BUILD_DIR}" || has_supported_sbt_1_version "${BUILD_DIR}"); then
   error "You have defined an unsupported sbt.version in project/build.properties
 For sbt 0.x you must use a version >= 0.11, for sbt 1.x you must use a version >= 1.1"
 fi
@@ -128,7 +137,7 @@ $ heroku config:set KEEP_PLAY_FORK_RUN=true"
   rm project/play-fork-run.sbt
 fi
 
-SBT_VERSION="$(get_supported_sbt_version ${BUILD_DIR})"
+SBT_VERSION="$(get_supported_sbt_version "${BUILD_DIR}")"
 
 if [ -n "$SBT_PROJECT" ]; then
   SBT_TASKS="$SBT_PROJECT/compile $SBT_PROJECT/stage"
@@ -150,43 +159,44 @@ fi
 install_sbt_extras "$OPT_DIR" "$SBT_BINDIR"
 
 # copy in heroku sbt plugin
-if has_supported_sbt_1_version ${BUILD_DIR}; then
+if has_supported_sbt_1_version "${BUILD_DIR}"; then
   HEROKU_PLUGIN="HerokuBuildpackPlugin_sbt1.scala"
 else
   HEROKU_PLUGIN="HerokuBuildpackPlugin.scala"
 fi
 mkdir -p "$SBT_USER_HOME/plugins"
-rm -f $SBT_USER_HOME/plugins/HerokuPlugin.scala # remove the old ambiguously named plugin
-rm -f $SBT_USER_HOME/plugins/HerokuBuildpackPlugin_sbt1.scala # remove the old poorly named plugin
-rm -f $SBT_USER_HOME/plugins/HerokuBuildpackPlugin.scala # remove the old plugin
-cp -p $OPT_DIR/$HEROKU_PLUGIN $SBT_USER_HOME/plugins/HerokuBuildpackPlugin.scala
+rm -f "$SBT_USER_HOME/plugins/HerokuPlugin.scala" # remove the old ambiguously named plugin
+rm -f "$SBT_USER_HOME/plugins/HerokuBuildpackPlugin_sbt1.scala" # remove the old poorly named plugin
+rm -f "$SBT_USER_HOME/plugins/HerokuBuildpackPlugin.scala" # remove the old plugin
+cp -p "$OPT_DIR/$HEROKU_PLUGIN" "$SBT_USER_HOME/plugins/HerokuBuildpackPlugin.scala"
 
 # Collect metrics
 metrics::set_string "sbt_version" "${SBT_VERSION:-unknown}"
 
-if is_sbt_native_packager $BUILD_DIR; then
+if is_sbt_native_packager "$BUILD_DIR"; then
   metrics::set_raw "uses_sbt_native_packager" "true"
 else
   metrics::set_raw "uses_sbt_native_packager" "false"
 fi
 
-if is_play $BUILD_DIR; then
+if is_play "$BUILD_DIR"; then
   metrics::set_raw "is_play_app" "true"
 else
   metrics::set_raw "is_play_app" "false"
 fi
 
 # Manually pre-clean because sbt-native-packager doesn't clobber this dir
-rm -rf $BUILD_DIR/target/universal/stage
+rm -rf "$BUILD_DIR/target/universal/stage"
 
 # download and cache the dependencies if this is the first build
 if [ ! -d "$SBT_USER_HOME/.ivy2" ]; then
-  if is_sbt_native_packager $BUILD_DIR || is_play $BUILD_DIR; then
+  if is_sbt_native_packager "$BUILD_DIR" || is_play "$BUILD_DIR"; then
     prime_ivy_cache "$BUILD_DIR" "$SBT_USER_HOME_ABSOLUTE" "$SBT_BINDIR/$SBT_JAR"
   fi
 fi
 
 # build app
+javaVersion="${JAVA_VERSION:-8}"
 run_sbt "$javaVersion" "$SBT_USER_HOME_ABSOLUTE" "$SBT_BINDIR/$SBT_JAR" "$SBT_TASKS"
 
 if [ -z "${DISABLE_DEPENDENCY_CLASSPATH_LOG:-}" ]; then
@@ -194,40 +204,40 @@ if [ -z "${DISABLE_DEPENDENCY_CLASSPATH_LOG:-}" ]; then
 fi
 
 # repack cache
-mkdir -p $CACHE_DIR
+mkdir -p "$CACHE_DIR"
 for DIR in $CACHED_DIRS; do
-  cache_copy $DIR $BUILD_DIR $CACHE_DIR
+  cache_copy "$DIR" "$BUILD_DIR" "$CACHE_DIR"
 done
 
 # drop useless directories from slug for play and sbt-native-launcher only
-if is_sbt_native_packager $BUILD_DIR || is_play $BUILD_DIR; then
+if is_sbt_native_packager "$BUILD_DIR" || is_play "$BUILD_DIR"; then
   if [ "$KEEP_SBT_CACHE" != "true" ]; then
-    if [ "$KEEP_IVY_CACHE" != "true" ] && [ -d $SBT_USER_HOME/.ivy2 ]; then
+    if [ "$KEEP_IVY_CACHE" != "true" ] && [ -d "$SBT_USER_HOME/.ivy2" ]; then
       status "Dropping ivy cache from the slug"
-      rm -rf $SBT_USER_HOME/.ivy2
+      rm -rf "${SBT_USER_HOME:?}/.ivy2"
     fi
-    if [ "$KEEP_COURSIER_CACHE" != "true" ] && [ -d $SBT_USER_HOME/.coursier ]; then
+    if [ "$KEEP_COURSIER_CACHE" != "true" ] && [ -d "$SBT_USER_HOME/.coursier" ]; then
       status "Dropping coursier cache from the slug"
-      rm -rf $SBT_USER_HOME/.coursier
+      rm -rf "${SBT_USER_HOME:?}/.coursier"
     fi
-    if [ -d $SBT_USER_HOME/boot ] ; then
+    if [ -d "$SBT_USER_HOME/boot" ] ; then
       status "Dropping sbt boot dir from the slug"
-      rm -rf $SBT_USER_HOME/boot
+      rm -rf "${SBT_USER_HOME:?}/boot"
     fi
-    if [ -d $SBT_USER_HOME/.cache ] ; then
+    if [ -d "$SBT_USER_HOME/.cache" ] ; then
       status "Dropping sbt cache dir from the slug"
-      rm -rf $SBT_USER_HOME/.cache
+      rm -rf "${SBT_USER_HOME:?}/.cache"
     fi
-    if [ -d $BUILD_DIR/project/boot ] ; then
+    if [ -d "$BUILD_DIR/project/boot" ] ; then
       status "Dropping project boot dir from the slug"
-      rm -rf $BUILD_DIR/project/boot
+      rm -rf "$BUILD_DIR/project/boot"
     fi
-    if [ -d $BUILD_DIR/target ] ; then
+    if [ -d "$BUILD_DIR/target" ] ; then
       status "Dropping compilation artifacts from the slug"
-      rm -rf $BUILD_DIR/target/scala-*
-      rm -rf $BUILD_DIR/target/streams
-      if [ -d $BUILD_DIR/target/resolution-cache ] ; then
-        find $BUILD_DIR/target/resolution-cache/* ! -name "reports" ! -name "*-compile.xml" -print0 | xargs -0 rm -rf --
+      rm -rf "$BUILD_DIR/target/scala-"*
+      rm -rf "$BUILD_DIR/target/streams"
+      if [ -d "$BUILD_DIR/target/resolution-cache" ] ; then
+        find "$BUILD_DIR/target/resolution-cache"/* ! -name "reports" ! -name "*-compile.xml" -print0 | xargs -0 rm -rf --
       fi
     fi
   fi
@@ -235,15 +245,15 @@ fi
 
 # write profile.d script
 profileScript="${BUILD_DIR}/.profile.d/scala.sh"
-mkdir -p $(dirname $profileScript)
-cat << EOF > $profileScript
+mkdir -p "$(dirname "$profileScript")"
+cat << EOF > "$profileScript"
 export SBT_HOME="\$HOME/$SBT_USER_HOME"
 export PATH="\$SBT_HOME/bin:\$PATH"
 EOF
 
 # Move compiled app back to where Heroku expects it
 if [ -z "${CNB_STACK_ID:-}" ] && is_app_dir "$APP_BUILD_DIR"; then
-  mv $BUILD_DIR $APP_BUILD_DIR
+  mv "$BUILD_DIR" "$APP_BUILD_DIR"
 fi
 
 # write export script
