replace sed piping on downloads with useful error

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -68,11 +68,7 @@ if [ ! -f "$SBT_BINDIR"/"$SBT_JAR" ]; then
   /bin/rm -f sbt sbt-launch-*.jar || true
 
   echo "-----> Building app with sbt"
-  curl --silent --max-time 60 -O --location $SBT_URL --fail 2>&1 | sed -u 's/^/       /'
-  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-    echo " !     Failed to download sbt-launch.jar"
-    exit 1
-  fi
+  curl --silent --max-time 60 -O --location $SBT_URL --fail || error "Failed to download $SBT_JAR"
 
   echo "#!/usr/bin/env bash" > sbt
   echo "/usr/bin/java -Dsbt.boot.properties=/app/.sbt_home/bin/sbt.boot.properties  -Duser.home=/app/.sbt_home -Divy.default.ivy.user.dir=/app/.sbt_home/.ivy2 -jar /app/.sbt_home/bin/$SBT_JAR \"\$@\"" >> sbt
@@ -86,28 +82,16 @@ if [ ! -f "$SBT_BINDIR"/"$SBT_JAR" ]; then
   cd $BUILD_DIR
 fi
 
-curl --silent --max-time 10 --location $SBT_PROPS_URL --output "$SBT_BINDIR"/sbt.boot.properties --fail 2>&1 | sed -u 's/^/       /'
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to download sbt.boot.properties"
-  exit 1
-fi
+curl --silent --max-time 10 --location $SBT_PROPS_URL --output "$SBT_BINDIR"/sbt.boot.properties --fail || error "Failed to download $SBT_PROPS"
 
 HEROKU_PLUGIN="Heroku-0.11.3.scala"
 mkdir -p "$SBT_USER_HOME/.sbt/plugins"
-curl --silent --max-time 10 --location "http://s3.amazonaws.com/heroku-jvm-langpack-scala/$HEROKU_PLUGIN" --output "$SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGIN" --fail 2>&1 | sed -u 's/^/       /'
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to download $HEROKU_PLUGIN"
-  exit 1
-fi
+curl --silent --max-time 10 --location "http://s3.amazonaws.com/heroku-jvm-langpack-scala/$HEROKU_PLUGIN" --output "$SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGIN" --fail || error "Failed to download $HEROKU_PLUGIN"
 
 
 HEROKU_PLUGINS_CONFIG="heroku-plugins-0.11.3.sbt"
 mkdir -p "$SBT_USER_HOME/.sbt/plugins"
-curl --silent --max-time 10 --location "http://s3.amazonaws.com/heroku-jvm-langpack-scala/$HEROKU_PLUGINS_CONFIG"  --output "$SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGINS_CONFIG" --fail 2>&1 | sed -u 's/^/       /'
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to download $HEROKU_PLUGINS_CONFIG"
-  exit 1
-fi
+curl --silent --max-time 10 --location "http://s3.amazonaws.com/heroku-jvm-langpack-scala/$HEROKU_PLUGINS_CONFIG"  --output "$SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGINS_CONFIG" --fail || error "Failed to download $HEROKU_PLUGINS_CONFIG"
 
 # build app
 echo "-----> Running: sbt $SBT_TASKS"
